AllCops:
  DisplayCopNames: true

#
# Style
#

LineLength:
  Max: 128

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SpaceBeforeFirstArg:
  Enabled: false

Style/GlobalVars:
  Enabled: false

#
# Metrics
#

Metrics/MethodLength:
  Max: 22

Metrics/AbcSize:
  Max: 20

AllCops:
  Include:
    - '**/Rakefile'
  Exclude:
    - 'spec/**/*'
